Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import sympy as sym

A = sym.Matrix([[1, -3], [4, 2]])
B = sym.Matrix([[3, 0], [-1, 5]])
C = sym.Matrix([[5], [9]])
D = sym.Matrix([[1, 1, 3], [4, -2, 3]])
E = sym.Matrix([[1, 2], [0, 6], [-2, 3]])
F = sym.Matrix([[1, -2, 4]])
G = sym.Matrix([[4, 2, 3], [-2, 6, 0], [0, 7, 1]])
H = sym.Matrix([[1, 0, 1], [5, 2, -2], [2, -3, 4]])

# Exercise 1.4
# (a)
AplusB = A + B
print("(a)")
display(AplusB)

# (b) B + C is undefined

# (c)
AT = A.T
print("(c)")
display(AT)

# (d)
CT = C.T
print("(d)")
display(CT)

# (e)
DplusET = D + E.T
print("(e)")
display(DplusET)

# (d)
threeBminusA = 3 * B - A
print("(f)")
display(threeBminusA)

# (g) E + F^T is undefined

# (h)
FTT = F.T.T
print("(h)")
display(FTT)

# (i)
twoGplusH = 2 * (G + H)
print("(i)")
display(twoGplusH)

# (j)
ATplusBT = A.T + B.T
print("(j)")
display(ATplusBT)

# (k)
AplusBT = (A + B).T
print("(k)")
display(AplusBT)

# (l)
minusG = -G
print("(l)")
display(minusG)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn [1], line 1[0m
[0;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01msympy[39;00m [38;5;28;01mas[39;00m [38;5;21;01msym[39;00m
[1;32m      3[0m A [38;5;241m=[39m sym[38;5;241m.[39mMatrix([[[38;5;241m1[39m, [38;5;241m-[39m[38;5;241m3[39m], [[38;5;241m4[39m, [38;5;241m2[39m]])
[1;32m      4[0m B [38;5;241m=[39m sym[38;5;241m.[39mMatrix([[[38;5;241m3[39m, [38;5;241m0[39m], [[38;5;241m-[39m[38;5;241m1[39m, [38;5;241m5[39m]])

[0;31mModuleNotFoundError[0m: No module named 'sympy'
ModuleNotFoundError: No module named 'sympy'

